### ISSUE TITLE
What kind of expression values as input?

### ISSUE THREAD

**Issue by komalsrathi** [cansysbio/ConsensusTME#2]
Hi!

I am going to try ConsensusTME. I might have missed it in the README/publication but cannot find as to what kind of expression values are allowed as input: FPKM/log2 counts/raw counts/TPM?

Please let me know.

Thanks!

**Comment by olliecast** [comment]
Hi Komal, 

We currently consider TPM to be the best input for the ssGSEA framework since it best captures the relative abundance of different gene expression. 

We haven't however benchmarked this (something on my to do list).

Ollie
